### ISSUE TITLE
Vehicles Replace Breaking Texture

### ISSUE THREAD

**Issue by ZwinkaDink** [rsrp-dev/DSISC#15]
Describe the bug
A clear and concise description of what the bug is. When you fully upggrade these vehicles, it will break all the textures in the server for a short distance.

To Reproduce
1. Go to 'Log Into Server'
2. Click on 'FileZilla'
3. Scroll down to 'Stream'
4. Remove these replaceable cars
5. spawn these vehicles, and fully upgrade them. 
6. Drive at the Airstrip to test them.

Expected behavior
They should not break the textures, and should be working perfectly fine.

Screenshots

Additional context
Here is the spawn names of the vehicles, Hermes,
Lurcher,
Hustler,
Moonbean Custom,
Nightshade,
Virgo,
Yiseris,
Comet SR,
Flash GT,
Futo,
Penumbra,
Schafter,
Sentinel Classic,
Minican Custom,

Submitted By:Kyle Jeens

**Comment by aguy96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Texture issues](https://trello.com/c/wyexayGw/51-texture-issues)
