### ISSUE TITLE
torque boost doesn't apply

### ISSUE THREAD

**Issue by ZwinkaDink** [rsrp-dev/DSISC#4]
Describe the bug
You can turn on torque boost, can check the box, can change the numbers to any value that they have, but it simply doesn’t do anything in game.

To Reproduce
1. Go to 'f1>vehicle options>torque settings’
2. Click on 'any torque option’
3. Try to drive

Expected behavior
I expected torque to kick in and my car actually to go faster

Screenshots
idk if u really need screenshots of torque

Additional context
doesn’t work at all and it kinda sucks.. but power boost works because billy told me

**Comment by ZwinkaDink** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [torque boost not saveing](https://trello.com/c/AwlG3vYL/58-torque-boost-not-saveing)

**Comment by aguy96** [comment]
Creator of VMenu stated Torque Boost should be working standalone, any issues are probably other resources

**Comment by ZwinkaDink** [comment]
that is what i told silent i dug into the DLLs and the code is the exact same as the power function and no one has said anything about it not working. and did they say anything what cars handeling script may effect it.

**Comment by ZwinkaDink** [comment]
cced226a752cdbb5db835eaa568c032d1e174328 fixed issue with the torque
